<div>
<p>
You can now access your 1098-T Tax document Online
What is 1098-T?
1098-T is to help you and/or your tax professional determine if you are eligible for any tax credit or deductions based on the amount of tuition and fees billed to the student, scholarships and grants received for the student by the college. Read the frequently asked question section to learn more.
Why sign up for an electronic version?
-	File your taxes early! No need to wait until February to receive 1098-T by mail
-	Free online access 24/7.
-	Save paper
Consent Form
IRS regulations state that each student who files a request to receive a 1098-T electronically must also provide his/her consent electronically.

By clicking on Grant Consent, you state your intent to receive your 1098-T form electronically. With this consent for an on-line electronic 1098-T, please understand that a paper copy of your 1098-T will not be mailed.

If you elect not to consent, a paper copy of your 1098-T will be sent to you via First Class US Mail to the address currently on file with ENC.
</p>
</div>