
<div><br />
<h1> Tuition Subsidy & Educational Allowance </h1>
<p>Educational allowance is a benefit received by some <strong>employees of
the Seventh-day Adventist Church</strong>. If one or both of your parents
<strong>are entitled to this benefit</strong> because of denominational employment in the
U.S., Canada, or the General Conference of Seventh-Day Adventists, please provide the name of the eligible parent and the conference name.</p>
<br /><br />
</div>

