<div id="megatopregion">
   <div id="loginline"><ul>
      <li style="display:none">d</li>
      <li class="home"><a href="http://www.epa.gov" target="_blank">EPA Home</a></li>
      <li class="emailicon"><a href=".\wStartUpUserLogin.jsp" target="_blank">Login</a></li>
      <li class="logoff"><a href="#" onclick="gLogout()">Logout</a></li>
      <li class="helpicon"><a href=".\wSystemDisplayHelpMessage.jsp" target="_blank">Help</a></li>
   </ul></div>
</div>
<div id="header">
   <!-- Logo-->
   <div id="logo">
      <!--Page Title <h1>&nbsp;</h1> --> 
      <!--Page Title <h1 style="opacity: 0.4; margin-top:0;padding-top:0;float:right;"><%=strBannerTitle%></h1> -->
      <!-- Before Logo-->
   </div><br /><br />
   <div id="wai" style="color:#cccccc; opacity:0.6; margin-top:40;border-top:40;padding-top:40;padding-right:40;float:right;font-size: 200%;"></div>

   <!--Top Menu-->
   <!-- If we wanted to get the menu on the banner. dCommented out for the moment- AS 7/31/2009-->
   <!--
   <div id="menu">
      <ul>
         <li class="active"><a href="#">ePamms Home</a></li>
         <li><a href="#">My Account</a></li>
         <li class="logoff"><a href="#">Log Out</a></li>
      </ul>
   </div>
   -->
<!-- Before Header-->
</div>
