<div id="megatopregion">
   <div id="loginline"><ul>

      <li class="home"><a href="http://www.epa.gov" target="_blank">dEPA Home</a></li>
      <li class="emailicon"><a href=".\wStartUpUserLogin.jsp" target="_blank">Login</a></li>
      <li class="logoff"><a href="#" onclick="mLogout()">Log Out</a></li>
      <li class="helpicon"><a href=".\wSystemDisplayHelpMessage.jsp" target="_self">Help</a></li>
   </ul></div>
</div>

<div id="header">
   <!-- Logo-->
   <div id="logo">
      <!--Page Title --> <h1>&nbsp;</h1>
      <!-- Before Logo-->
   </div>

   <!--Top Menu-->
   <!-- If we wanted to get the menu on the banner. Commented out for the moment- AS 7/31/2009-->
   <!--
   <div id="menu">
      <ul>
         <li class="active"><a href="#">ePamms Home</a></li>
         <li><a href="#">My Account</a></li>
         <li class="logoff"><a href="#">Log Out</a></li>
      </ul>
   </div>
   -->
<!-- Before Header-->
</div>