<div style="clear:both;"></div>
<div id="footer" >

<div style="float:right;">

<table style="width:750px;background-color:black;color:white;border:none;font-size:8px;">
<tr style="background-color:black;color:white;border:none;">

<td nowrap style="background-color:black;color:white;border:none;padding-top:3px;font-size:11px;">Eastern Nazarene College</td>
<td nowrap style="background-color:black;color:white;border:none;padding-top:3px;font-size:11px;">23 East Elm Avenue</td>
<td nowrap style="background-color:black;color:white;border:none;padding-top:3px;font-size:11px;">Quincy, Massachusetts 02170</td>
<td nowrap style="background-color:black;color:white;border:none;padding-top:3px;font-size:11px;">Questions? E-mail us at <a href="mailto:myenchelp@enc.edu">myenchelp@enc.edu</a></td>

</tr>
</table>

</div>

</div>