<div id="footer">
				<div id="leftfoot">
					<p>Eastern Nazarene College <img src="images/footer_address_dot.gif" width="6" height="6" /> 23 East Elm Avenue <img src="images/footer_address_dot.gif" width="6" height="6" />Quincy, Massachusetts 02170 <img src="images/footer_address_dot.gif" width="6" height="6" /> 1.617.745.3000 <img src="images/footer_address_dot.gif" width="6" height="6" /> 1.800.88.ENC.88 </p>
</div>
			  <div id="centerfoot">
					
</div>            
				<div id="rightfoot">
					<p>Questiions? Email myenchelp@enc.edu<br />
Phone Number: 617 745 3727<br />
Information Technology Services<br />
					</p>
	  </div>
			</div>