<div class="container_16">

<div class="full_width" style="height:20px"></div>

	
<div class="full_width" id="wrap_footer">    
        	<div class="full_width" id="footer_shadow"></div>
        
        
	  <div class="grid_4 omega" id="footer_address"><img src="../images/enc/seal_footer.gif" /><br />Eastern Nazarene College<br />
  23 East Elm Avenue<br />
  Quincy, Massachusetts 02170<br />
  1-617-745-3000<br />
  1-800-88-ENC-88
  			</div>
        
                <div class="grid_2 footer_links">
                   
               </div>
        
	      <div class="grid_2 footer_links">
	        <p><a href="#">Academic Calendar</a></p>
       		      <p><a href="#">Campus Camera Newspaper</a></p>
       		      <p><a href="#">Career Services</a></p>
       		      <p><a href="#">Counseling Services</a></p>
       		      <p><a href="#">Christian Scholar</a></p>
       		    </div>
               
                <div class="grid_2 footer_links">
                   
               </div>
               
               <div class="grid_2 footer_links">test
                   
               </div>
               
                <div class="grid_2 footer_links">test
                   
               </div>
               
               <div class="grid_2 footer_links omega">
                   
               </div>
  


  </div>
        <div class="full_width" id="footer_bottom">
            <div class="grid_1 alpha omega" id="bl"></div>
            <div class="grid_14 alpha omega" id="bc"></div>
            <div class="grid_1 alpha omega" id="br"></div>
        </div>

</div>

<div class="full_width" style="height:20px"></div>