<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome to MyENC</title>
</head>
<body>
<script language="JavaScript">
//<!-- Temporary redirection from jsp to http://www1.enc.edu/department-home.aspx?id=535 10/7/2009-->
//<!--
function redirect()
{
   window.location = "http://www1.enc.edu/applicationthankyou"
}

setTimeout( "redirect( );", 0 )
//-->
</script>

 <div>
	<p><img src="/images/wait.gif" />
	Welcome to MyENC</p>
	Redirecting
</div>

</body>
</html>

