
<div style="color:#000000;font-size: 16px">
<p>Health Insurance</p>
</div>
<div class="borderbottomnw"></div>
<div><br />
<p>
<p> If you do not provide evidence of other coverage, you must participate in the health insurance 
program endorsed by Southwestern Adventist Universityk.</p><br />
</div>
<div>
<p><strong>View: <a href="https://sharepoint.swau.edu/public/Shared%20Documents/Insurance/InsurancePolicy-2010-2011.pdf" target="_blank">Health Insurance Brochure</a>
</strong><br />
</div>
<div>
<p><strong>View: <a href="https://sharepoint.swau.edu/public/Shared%20Documents/Insurance/InsuranceDependentEnrollment-2010-2011.pdf" target="_blank">Spouse & Dependent Enrollment</a>
</strong><br />
</div>
