<div style="color:#000000;font-size: 18px">
<p>The Rusty Bucket</p>
</div>
<p>
<div class="borderbottomnw"></div>

<div style="color: #000000">
  The Rustry Bucket is a snack store located inside the cafeteria.  Rusty Bucket mealplans offer 20% of your meal plan dollars for flexible
use.  This money may be used for snacks, guest meals, or meal replacement when you cannot make it to a regular cafeteria meal.</p><p>
</div>
<p><strong>Hours</strong><br />  <br />
<div style="color: #000000">  
<p>8:30a - 6:30p Monday through Thursday</p>
<p>8:30a - 5:00p Friday</p>
</div>

<div style="color:#000000;font-size: 18px">
<p>The Fine Print</p>
</div>
<p>
<div class="borderbottomnw"></div>

  <p>SWAU Foodservice is not an all-you-can-eat facility. While our buffet
  is self-serve, items such as entrées (and/or other items) may be limited
  due to availability, cost, and production issues. Food waste is always an
  area of concern with self-serve buffet service and we ask that you eat
  what you take and take no more than you can eat.</p>
 
  <ul>
   <li>There is a $15 per day spending limit on all Rusty Bucket plans.</li>
   <li>Meal Plans do not include Christmas and Summer breaks.</li>
   <li>Meal plans are non-transferable and cannot be shared.</li>
   <li>Unused Rusty Bucket dollars are not refundable.</li>
   <li>Unused meals do not carry over to the next week.</li>
  </ul>
<p> <br />

<object id="cafevideo" type="application/x-shockwave-flash" data="/OpenCUAS/video/cafe/player_flv_mini.swf" width="320" height="240">
<param name="movie" value="/OpenCUAS/video/cafe/player_flv_mini.swf" />
<param name="wmode" value="opaque" />
<param name="allowScriptAccess" value="sameDomain" />
<param name="quality" value="high" />
<param name="menu" value="true" />
<param name="autoplay" value="false" />
<param name="autoload" value="true" />
<param name="FlashVars" value="flv=/OpenCUAS/video/cafe/cafe_1.flv&width=320&height=240&autoplay=0&autoload=1&buffer=5&playercolor=000000 &loadingcolor=9b9a9a&buttoncolor=ffffff&slidercolor=ffffff" />
</object>

<!--
<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/y_fnKUnBDX4&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/y_fnKUnBDX4&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
-->
<p> <br />

<div style="color:#000000;font-size: 18px">
<p>Cancellation and Disciplinary Action</p>
</div>
<p>
<div class="borderbottomnw"></div>

  A student may have his/her meal plan contract cancelled in whole or in part or be subject to disciplinary action by Southwestern for the following reasons:
  <ul>
   <li>Any abuse: using abusive or insulting language, vandalism, abusing staff or facilities, and infringements upon the rights of others</li>
   <li>Removing food or equipment from the dining area (except food purchased in the Rusty Bucket)</li>
   <li>Excessive food waste, (consistently leaving  uneaten food on trays or abusing limited portion amounts)</li>
   <li>Allowing others to use your meal plan</li>
   <li>Displaying unacceptable conduct, disruptive behavior or personal endangerment of any kind. (For example: Throwing food or other objects.)</li>
  </ul>
