<!-- <div align="center" class="footer">
   <a href="About ENC.html">About | </a>
   <a href="">Undergraduate | </a>
   <a href="">Graduate | </a>
   <a href="">Adult Studies | </a>
   <a href="">Resources | </a>
   <a href="">Athletics | </a>
   <a href="">News | </a>
   <a href="">Alumni</a>
<ul>
<li>Eastern Nazarene College</li>
<li>23 East Elm Avenue</li>
<li>Quincy, Massachusets 02170</li>
</ul>
-->
</div>
</body>
</html>
