<!-- start banner -->
<div id="bannernew"><img src="images/top_ENCbanner.jpg" width="800" height="93"></div>
<!-- start nav -->
   <!--First row of Top navigation-->
   <div id="nav">
   <ul>
      <li><a href="#">Admissions |</a></li>
      <li><a href="#">Financial Aid |</a></li>
      <li><a href="#">Billing |</a></li>
      <li><a href="#">Academics |</a></li>
      <li><a href="#">Athletics |</a></li>
      <li><a href="#">Student Life |</a></li>
      <li><a href="#">Calendars |</a></li>
      <li><a href="#">Library |</a></li>
      <li><a href="#">Resources|</a></li>
      <li><a href="wPortalDStudentLogin.jsp">MyENC.edu</a></li>
   </ul>
   </div>

<!-- second row of top navigation begins -->
   <div id="nav2">
   <ul>
      <li><a href="#">Prospective Students |</a></li>
      <li><a href="#">Undergraduate |</a></li>
      <li><a href="#">Adult Studies |</a></li>
      <li><a href="#">Graduate Studies |</a></li>
      <li><a href="#">Parents |</a></li>
      <li><a href="#">Alumni |</a></li>
      <li><a href="#">Donors |</a></li>
      <li><a href="#">Churches |</a></li>
      <li><a href="#">Faculty/Staff </a></li>
   </ul>
   </div>
 <!--second row ends-->
<span>
   <div id="small_corner_banner"><img src="images/blackcornerbanner.gif" width="144" height="24">
   </div>
</span>

