<div id="leftnavigation">
   <ul>
      <li><a href="PresidentsMessage.html">President's Message</a></li>
       <li><a href="http://www.enc.edu/~mcclung/index.html" target="_blank">The President's Photo Album</a></li>
       <li><a href="MissionStatement.html">Mission</a></li>
       <li><a href="LocationsAndDirections.html">Location & Directions</a></li>
       <li><a href="Photo Tour.html">Photo Tour</a></li>
       <li><a href="Accreditations and Affiliations.html">Accredations & Affiliations</a></li>
       <li><a href="Spiritual Emphasis.html">Spiritual Emphasis</a></li>
       <li><a href="Honored Faculty and Staff.html">Honored Faculty & Staff</a></li>
       <li><a href="Faculty Biographies.html">Faculty Biographies</a></li>
       <li><a href="wOLAppDemoPage1.jsp">Undergraduate Application</a></li>
   </ul>
</div>

