<!-- start banner -->
<div id="bannernew">
<a href="/zencas/wPortalDStudentLogin.jsp"><img src="images/top_MYENCbanner.jpg" width="800" height="93"></a></div>
<!-- start nav -->
   <!--First row of Top navigation-->
   <div id="nav">
   <ul>
      <li><a href="/zencas/wPortalDStudentHomePage.jsp">Profile |</a></li>
      <li><a href="/zencas/wPortalDProspectHomePage.jsp">Prospects |</a></li>
      <li><a href="/zencas/wPortalDStudentAccounts.jsp">Billing |</a></li>
      <li><a href="#">Financial Aid|</a></li>
      <li><a href="/zencas/wPortalDRegistrar.jsp">Registrar |</a></li>
      <li><a href="#">Student Life |</a></li>
      <li><a href="#">Calendars |</a></li>
      <li><a href="#">Library |</a></li>
      <li><a href="http://webmail.enc.edu" target="_new">EMail|</a></li>
</ul>
   </div>

<!-- second row of top navigation begins -->
   <div id="nav2">
   <ul>
      <li>_</li>
   </ul>
   </div>
<!--second row ends-->
<span>
   <div id="small_corner_banner"><img src="images/blackcornerbanner.gif" width="144" height="24">
   </div>
</span>

