<div class="text14bold">
<div  style="width:230px;">
                    <div style="background-color: #F9F9F9;border: 1px solid #9BBB59;padding-right: 15px;padding-bottom: 3px;padding-left: 15px;
	font-family: Arial, sans-serif;	font-size: small;line-height: 1.4em;" align="center">
                      <p><strong> Take Advantage of these Special Offers available to ENC students, faculty and staff ONLY!!!</strong></p>
                      <p><a href="http://enc.edu/its"><img src="../images/misc/windows7.JPG" alt="Windows 7 @ $59!!!" width="100" height="111" border="0" /></a></p>
                      <p><a href="http://enc.edu/its" target="_blank">Compare Online at  $199 and $219 </a><br><br />
                        <br>
                      </p>
                      <p><a href="http://premier.dell.com/premier/?331427DD527495E6EED58B8E828511310D72D707370CB765C2795DD45D98AC81596CD99DE283FD2D" target="_blank"><img src="../images/misc/dell-logo.jpg" alt="" width="100" height="102" border="0" /></a></p><br />
                      <p><a href="http://premier.dell.com/premier/?331427DD527495E6EED58B8E828511310D72D707370CB765C2795DD45D98AC81596CD99DE283FD2D" target="_blank">Dell University Program</a></p><br />
                      <p><a href="http://enc.edu/its" target="_blank"><img src="../images/misc/office2007.jpg" alt="Office Enterprise 2007 for only $59!!!" width="100" height="100" border="0" /></a></p><br />
                      <p><a href="http://enc.edu/its" target="_blank">Office Enterprise 2007</a></p><br />
                      <p><a href="http://enc.edu/its" target="_blank"><img src="../images/misc/e2campus.png" alt="ENC Campus Alert System" width="178" height="52" border="0" /></a></p>
                      <p><a href="http://enc.edu/its" target="_blank">Sign up FREE for ENC Alerts</a><a href="../../children/index.html" target="_parent"><br><br />
                      </a></p>
    </div>
                  </div>

</div>