
<div style="color:#000000;font-size: 18px">
<p>Welcome to Information Technology Services at ENC</p><br /><br />

</div>
<p>
<p> PLEASE READ THE INFORMATION BELOW BEFORE ACTIVATING YOUR  NETID.</p><br />
<div class="borderbottomnw">
<p><strong>What is a NetID?<br />
</strong><br />
</div>
<div style="color: #000000">
  NetID is your login credentials (username and password) to  access ENC's systems and applications with the same login and password.</p><p><br />
</div>
<div class="borderbottomnw"><p><strong>Why do I need a NetID?</strong><br />  <br /></div>
<div style="color: #000000">  <p>
  With NetID, you can log in to: <a href="http://my.enc.edu" target="_blank">Student/Employee Portal:  MyENC</a>, <a href="http://owa.enc.edu" target="_blank">Email: Outlook Web Access (OWA)</a>, <a href="http://enc.edu/wireless" target="_blank">Secure Wireless</a>, <a href="http://library.enc.edu" target="_blank">Remote Library Access</a>, <a href="http://moodle.enc.edu" target="_blank">Online  Learning Management System: Moodle</a>, Computer Labs.</p>
  <br />
</div>
<div class="borderbottomnw">
  <p><strong>What is my NetID?<br /></strong><br />
    </p>
  </div>
<div style="color: #000000">
  <p>
    NetID is generally the first seven letters of the last name and first initial. Your NetID will be revealed to you at the end of the activation process.</p><br />
</div>
<div class="borderbottomnw">
  <p><strong>Do I also get an ENC email address?<br /> </strong><br />
  </p>
</div>
<div style="color: #000000">
  <p>Yes. The College has established the policy that it will  use email to send official communication to students. In order to correspond this way, a standard  official @enc.edu email address will automatically be assigned when you  become a student. You will be responsible for information sent  to your ENC e-mail address.<strong></strong> Normally, the format of the email address is: &lt;firstname&gt;.&lt;middleinitial&gt;.&lt;lastname&gt;@enc.edu</p>
  <p><br />
</p>
</div>
<div class="borderbottomnw">
    <p><strong>Who do I contact if I have a  problem/question?<br />
      </strong><br />
    </p>
</div>
<div style="color: #000000">
  <p>Business Hours: Mon - Fri, 8 A.M - 5 P.M.</p>
  <p>Open a HelpDesk ticket: Send an email from your ENC email address to its-help@enc.edu</p>
  <p>Stop by our office at the Basement Gardner Building.</p>
  <p>Call us at: (617) 745-3727</p>
  <p>Website: <a href="http://enc.edu/its" target="_blank">http://enc.edu/its</a></p>
  <p>&nbsp;</p>

</div>
<div class="alert">
  <p>REMINDER: Do NOT share your password with anyone. ITS will  NEVER ask for it via email or over the phone. Any request for your password is  a scam and should be ignored. <br />
  </p>
</div>
