
<div>
<p>To reserve a room, students are required to pay a general deposit of $100
to the respective residence hall. The deposit will be held until the student
graduates, moves out of the residence hall, or withdraws from the
university. The deposit is refundable on condition that the checkout
procedure of the residence hall is followed (see the 
<a href="https://sharepoint.swau.edu/public/Shared%20Documents/Student%20Handbooks/ResidenceHallHandbook-2010-2011.pdf" target="_blank">Residence Hall Handbook</a>).
Should a student cancel an application for admission before August 18, the
deposit will be refunded.</p>
<br />
</div>

