<div style="color:#000000;font-size: 18px">
<p>Student Payroll Authorization</p>
</div>
<p>
<div class="borderbottomnw"></div>
<div style="color: #000000">
<p>Southwestern Adventist University is committed to a student employment program whereby students may earn money to help pay their educational costs. If a student works on campus and wishes to participate in a payment plan that allows him/her to make payments over the semester, the student must give authorization for Southwestern to apply to their account:</p>
<ul>
<li>50% of their campus earnings if the student is current with their monthly payments</li>
<li>80% if they are not current with their monthly payments</li>
</ul>
<p>This includes Federal and State Work Study funds. Once the account is paid in full the student will receive the full paycheck.</p>
<p>If you have chosen either Payment Plan II or II, please give authorization for Southwestern to apply the above percentages of your campus wages to your student account when you are paid on the 1st of each month.</p>
</div>

