<div style="color:#000000;font-size: 18px">
<p>Payment Plans</p>
</div>
<p>
<div class="borderbottomnw"></div>

<div style="color: #000000">
<p>
<p> SWAU offers three payment plans for fall and spring semesters to help students manage their university expenses. Classes taken during the summer require full payment at the time of registration for each module.</p>
<h3>PLAN I — CASH</h3>
<p>When the total charges for a semester are paid on registration day, a discount of 3% is given on the cash paid for tuition, room, and board. (Before this discount is calculated, all scholarships, loans, grants, awards, other discounts, and university aid funds are subtracted.) Students using this plan must bring with them at registration time the full amount of the package plan, plus miscellaneous charges such as music lessons and private room fee. A cash discount is not given on post-baccalaureate student, ADP, or other discounted programs. This discount does not apply to payments made by credit or debit card.</p>
<h3>PLAN II — FIVE-PAYMENT SEMESTER AGREEMENT</h3>
<p>This plan is a five-payment contract with the University. The first payment is 60% of semester charges, and financial aid can be applied toward this requirement. The remaining balance will be divided equally over four payments.</p>
<h3>PLAN III — FOUR-PAYMENT SEMESTER AGREEMENT</h3>
<p>This plan is a four payment contract with the University. A minimum of 60% will be paid at the time of registration, with financial aid as a part of that payment. The remaining balance will be divided into three payments.</p>
</p>
</div>
