<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="./css/zeidon_allrelative_prospect.css" rel="stylesheet" type="text/css">
<link href="./css/zeidon_prospect.css" rel="stylesheet" type="text/css">
<link href="./css/main.css" rel="stylesheet" type="text/css">
<link href="./css/aadit.css" rel="stylesheet" type="text/css">

<!-- JQuery for Validations-->
<script src="./js/jquery.js" type="text/javascript"></script>
<script src="./js/jquery.maskedinput.js" type="text/javascript"></script>
<script language="JavaScript" type="text/javascript">

jQuery(function($){
   $("#DOB").mask("99/99/9999",{placeholder:" "});
   $("#edtMotherHPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtMotherCellPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtFatherHPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtFatherCellPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtRef1HPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtRef1CellPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtRef2HPhone").mask("999-999-9999",{placeholder:" "});
   $("#edtRef2CellPhone").mask("999-999-9999",{placeholder:" "});
   $("#CellPhone").mask("999-999-9999",{placeholder:" "});
   $("#CellPhone1").mask("999-999-9999",{placeholder:" "});
   $("#HomePhone").mask("999-999-9999",{placeholder:" "});
   $("#HomePhone1").mask("999-999-9999",{placeholder:" "});
   $("#SSN").mask("999-99-9999",{placeholder:" "});
});
</script>


