<div style="width: 998px" class="container_16">

        	
        	<div class="full_width" style="height:20px; width: 998px">
		
			
				<div class="full_width" style="width: 998px" id="wrap_footer">    
        	<div class="full_width" style="width: 998px" id="footer_shadow"></div>
        
        
			<div class="grid_4 omega" id="footer_address"><img src="./images/seal_footer.gif" /><br />Eastern Nazarene College<br />
  23 East Elm Avenue<br />
  Quincy, Massachusetts 02170<br />
  1-617-745-3000<br />
  1-800-88-ENC-88
  			</div>
        
	<div class="grid_4 footer_links">
		<a href="http://www.enc.edu/academics/index.htm" target="_blank">Academics</a>
		<a href="http://www1.enc.edu/athletics/" target="_blank">Athletics</a>
		<a href="http://www1.enc.edu/visit/" target="_blank">Campus Visit</a>
		<a href="http://www1.enc.edu/About-ENC/Campus-Map.aspx" target="_blank">Campus Map</a>
		<a href="http://www1.enc.edu/Admissions/About/Living-On-Campus.aspx" target="_blank">Campus Living</a>
		<a href="http://www.enc.edu/goto/counseling/academic_services.htm " target="_blank">Center for Academic Services</a>
		
		 		  
	</div>
			
	<div class="grid_4 footer_links">
				<a href="http://www.enc.edu/academics/programs/index.htm" target="_blank">Degrees and Programs</a>
		<a href="http://www1.enc.edu/financialaid/" target="_blank">Financial Aid</a>
		<a href="http://www1.enc.edu/Admissions/About/Recommended-High-School-Preparation.aspx" target="_blank">High School Prep</a>
		<a href="http://www.enc.edu/academics/honors/honors_program.html" target="_blank">Honors Scholar Program</a>
		<a href="http://www1.enc.edu/Admissions/About/Meet-The-Enrollment-Counselors.aspx" target="_blank">Meet your counselor</a>
		<a href="http://www1.enc.edu/Admissions/Programs/Boston-Bound-Travel-Program.aspx" target="_blank">Travel Program</a>		
	</div>
				   
	<div class="grid_4 footer_links">
		<a href="http://www.facebook.com/pages/Quincy-MA/The-Eastern-Nazarene-College-ENC/54293223199" target="_blank"><img src="./images/facebook_ug.jpg" /></a>
		<a href="http://twitter.com/EasternNazarene " target="_blank"><img src="./images/twitter_logo.png" /></a>
	</div>
               

               
</div> 
        <div style="width: 998px" class="full_width" id="footer_bottom">
            <div class="grid_1 alpha omega" id="bl"></div>
            <div style="width: 958px"class="grid_14 alpha omega" id="bc"></div>
            <div class="grid_1 alpha omega" id="br"></div>
        </div>

</div>

<div class="full_width" style="height:20px"></div>
