<div class="grid_16" id="headerinquiry">

<a href="/default.aspx" ><img alt="logo" src="/images/logo.gif" id="logo_image" border="0"/></a>

    <ul id="headerinquiry_links">
    <li><a href="/default.aspx">HOME</a></li>
    <li><a href="https://my.enc.edu/zencas/wStartUpLogin.jsp">MyENC</a></li>
    <li><a href="http://www.enc.edu/calendar.htm">CALENDAR</a></li>

    <li><a href="/About-ENC/Location-and-Directions/">DIRECTIONS</a></li>
    <li><a href="http://www.enc.edu/cgi-bin/addrbook.cgi">DIRECTORY</a></li>
    <li><a href="http://www.enc.edu/contact_us.php">CONTACT</a></li>
    <li><a href="/apply/">APPLY</a></li>
    <li><a href="/giving">GIVING</a></li>
    </ul>        	  
	
</div>

<div id="mainnav_top">
        	<div id="navitems">
                <a href="http://www1.enc.edu/about/" class="first">ABOUT ENC</a>
                <a href="http://www.enc.edu/admissions/">ADMISSIONS</a>
                <a href="http://www.enc.edu/academics">ACADEMICS</a>
                <a href="http://www.enc.edu/athletics/">ATHLETICS</a>
                <a href="http://www.enc.edu/adult-studies/">ADULT STUDIES</a>
                <a href="http://library.enc.edu">LIBRARY</a>
                <a href="http://www1.enc.edu/services/">SERVICES</a>
		</div>
</div>

