<div id="sidenavigationenc">
   <ul>
	   <li><a href="http://www1.enc.edu/counselors/"  onclick="LOGOFF()"> Counselors</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/Application-Process/"> The Process</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/Transfer-Applicants/"  onclick="LOGOFF()"> Transfers</a></li>
	   <li><a href="http://www1.enc.edu/visit"> Campus Visit Event Dates</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/International-Applicants/"> International</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/Recommended-High-School-Preparation/"> High School Prep</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/Living-On-Campus/"> Campus Living</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/Programs/Boston-Bound-Travel-Program/"> Travel Program</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/Residence-Halls/"> Residences</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/About/Married-Student-Housing/"> Married Housing</a></li>
	   <li><a href="http://www1.enc.edu/subpage.aspx?fid=275"> Forms and Documents</a></li>
	   <li><a href="http://www1.enc.edu/Admissions/Contact-Admissions/"> Contact Admissions</a></li>
	   <li><a href="http://www1.enc.edu/WorkArea/linkit.aspx?LinkIdentifier=ID&ItemID=202"> Financial Aid</a></li>
   </ul>
</div> <!-- sidenavigation -->

