<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="./css/zeidon_allrelative.css" rel="stylesheet" type="text/css">
<link href="./css/zeidon.css" rel="stylesheet" type="text/css">

<!-- JQuery for Validations-->
<script src="./js/jquery.js" type="text/javascript"></script>
<script src="./js/jquery.maskedinput.js" type="text/javascript"></script>
<script language="JavaScript" type="text/javascript">

jQuery(function($){
   $("#DOB").mask("99/99/9999",{placeholder:" "});
   $("#SSN").mask("999-99-9999",{placeholder:" "});
});
</script>


