<div style="color:#000000;font-size: 18px">
<p>Title IV Authorization</p>
</div>
<p>
<div class="borderbottomnw"></div>
<div style="color: #000000">
<p>If your Federal Student Aid exceeds the tuition, fees, room and board charges, Southwestern Adventist University must have authorization to use these funds to cover any additional miscellaneous charges such as bookstore charges that are incurred on your account. <strong>You have the right to revoke this authorization to use federal student aid for miscellaneous charges at any time.</strong></p>

<p>When miscellaneous charges I have incurred at Southwestern Adventist University are charged to my student account (other than tuition, fees, room and board), the charges will be paid in the following manner:<p>
</div>

