<div style="width: 998px" class="container_16">

        	
        	<div class="full_width" style="height:20px; width: 998px">
		
			
				<div class="full_width" style="width: 998px" id="wrap_footer">    
        	<div class="full_width" style="width: 998px" id="footer_shadow"></div>
        
        
			<div class="grid_4 omega" id="footer_address"><img src="./images/epamms_logo_buttons.png" /><br />ePamms, Inc.<br />
  119 Russell Street, Suite 21<br />
  Littleton, MA  01460<br />
  978-486-3690 (office)<br />
  978-500-3455 (cell)
  			</div>
        
        <!-- Note: Always add a trailing slash to subfolder references. If you link like this: href="http://www.w3schools.com/html", you will generate two requests to the server,
             the server will first add a slash to the address, and then create a new request like this: href="http://www.w3schools.com/html/". -->

	<div class="grid_4 footer_links">
		<a href="http://www.epamms.com/" target="_blank">ePamms Website</a>
	</div>
			
	<div class="grid_4 footer_links">
                <a href="#" onclick="confirm('Web Development and Maintenance not yet implemented.');">Web Development & Maintenance</a>
                <a href="#" onclick="confirm('Marketing and Fulfillment not yet implemented.');">Marketing & Fulfillment</a>
                <a href="#" onclick="confirm('State Registrations not yet implemented.');">State Registrations</a>
                <a href="#" onclick="confirm('Tracking/Notification/Compliance not yet implemented.');">Tracking/Notification/Compliance</a>
           <!-- <a href="#" onclick="onclick="mSubregistrants()";">Subregistrant Maintenance</a> -->
	</div>
				   
	<div class="grid_4 footer_links">

		<a href="http://twitter.com/# " target="_blank"><img src="./images/twitter_logo.png" /></a>
	</div>
               

               
</div> 
        <div style="width: 998px" class="full_width" id="footer_bottom">
            <div class="grid_1 alpha omega" id="bl"></div>
            <div style="width: 958px"class="grid_14 alpha omega" id="bc"></div>
            <div class="grid_1 alpha omega" id="br"></div>
			
        </div>

</div>

<div class="full_width" style="height:20px"></div>
