call wd wMLCClaimsFootnoteStatement.js wMLCClaimsFootnoteStatement.js.hld
call wd wSLCMarketingStatement.js wSLCMarketingStatement.js.hld
call wd wSPLDGraphicalView.js wSPLDGraphicalView.js.hld
call wd wStartUpUserLogin.js wStartUpUserLogin.js.hld
call wd wSystemDisplayHelpMessage.js wSystemDisplayHelpMessage.js.hld
call wd wSystemDragDropSort.js wSystemDragDropSort.js.hld
call wd wSystemExitHelpMessage.js wSystemExitHelpMessage.js.hld
call wd wSystemUpdateHelpMessage.js wSystemUpdateHelpMessage.js.hld
call wd wMLCTableData.js wMLCTableData.js.hld