copy genjs\wSystemDisplayHelpMessage.js.hld genjs\wSystemDisplayHelpMessage.js
copy wSystemDisplayHelpMessage.jsp.hld wSystemDisplayHelpMessage.jsp
copy genjs\wSystemExitHelpMessage.js.hld genjs\wSystemExitHelpMessage.js
copy wSystemExitHelpMessage.jsp.hld wSystemExitHelpMessage.jsp
copy genjs\wSystemUpdateHelpMessage.js.hld genjs\wSystemUpdateHelpMessage.js
copy wSystemUpdateHelpMessage.jsp.hld wSystemUpdateHelpMessage.jsp
copy genjs\wSPLDGraphicalView.js.hld genjs\wSPLDGraphicalView.js
copy wSPLDGraphicalView.jsp.hld wSPLDGraphicalView.jsp
copy genjs\wStartUpUserLogin.js.hld genjs\wStartUpUserLogin.js
copy wStartUpUserLogin.jsp.hld wStartUpUserLogin.jsp
copy genjs\wSystemDragDropSort.js.hld genjs\wSystemDragDropSort.js
copy wSystemDragDropSort.jsp.hld wSystemDragDropSort.jsp