move wSPLDVersionData.jsp ..\..\hold\wSPLDVersionData.jsp
move genjs\wSPLDVersionData.js ..\..\hold\genjs\wSPLDVersionData.js
move wSPLDTemplateStructure.jsp ..\..\hold\wSPLDTemplateStructure.jsp
move genjs\wSPLDTemplateStructure.js ..\..\hold\genjs\wSPLDTemplateStructure.js
move wSPLDTemplateSectionDetail.jsp ..\..\hold\wSPLDTemplateSectionDetail.jsp
move genjs\wSPLDTemplateSectionDetail.js ..\..\hold\genjs\wSPLDTemplateSectionDetail.js
move wSPLDTemplatePanelDetail.jsp ..\..\hold\wSPLDTemplatePanelDetail.jsp
move genjs\wSPLDTemplatePanelDetail.js ..\..\hold\genjs\wSPLDTemplatePanelDetail.js
move wSPLDTemplateDetail.jsp ..\..\hold\wSPLDTemplateDetail.jsp
move genjs\wSPLDTemplateDetail.js ..\..\hold\genjs\wSPLDTemplateDetail.js
move wSPLDTemplateBlockDetail.jsp ..\..\hold\wSPLDTemplateBlockDetail.jsp
move genjs\wSPLDTemplateBlockDetail.js ..\..\hold\genjs\wSPLDTemplateBlockDetail.js
move wSPLDSurfacesStatement.jsp ..\..\hold\wSPLDSurfacesStatement.jsp
move genjs\wSPLDSurfacesStatement.js ..\..\hold\genjs\wSPLDSurfacesStatement.js
move wSPLDSurfaces.jsp ..\..\hold\wSPLDSurfaces.jsp
move genjs\wSPLDSurfaces.js ..\..\hold\genjs\wSPLDSurfaces.js
move wSPLDSubregLogin.jsp ..\..\hold\wSPLDSubregLogin.jsp
move genjs\wSPLDSubregLogin.js ..\..\hold\genjs\wSPLDSubregLogin.js
move wSPLDStorageDisposalStatement.jsp ..\..\hold\wSPLDStorageDisposalStatement.jsp
move genjs\wSPLDStorageDisposalStatement.js ..\..\hold\genjs\wSPLDStorageDisposalStatement.js
move wSPLDStorageDisposalSection.jsp ..\..\hold\wSPLDStorageDisposalSection.jsp
move genjs\wSPLDStorageDisposalSection.js ..\..\hold\genjs\wSPLDStorageDisposalSection.js
move wSPLDStorageDisposal.jsp ..\..\hold\wSPLDStorageDisposal.jsp
move genjs\wSPLDStorageDisposal.js ..\..\hold\genjs\wSPLDStorageDisposal.js
move wSPLDSPLDList.jsp ..\..\hold\wSPLDSPLDList.jsp
move genjs\wSPLDSPLDList.js ..\..\hold\genjs\wSPLDSPLDList.js
move wSPLDSelectMarketingSections.jsp ..\..\hold\wSPLDSelectMarketingSections.jsp
move genjs\wSPLDSelectMarketingSections.js ..\..\hold\genjs\wSPLDSelectMarketingSections.js
move wSPLDReselectTemplate.jsp ..\..\hold\wSPLDReselectTemplate.jsp
move genjs\wSPLDReselectTemplate.js ..\..\hold\genjs\wSPLDReselectTemplate.js
move wSPLDPrecautionaryStatement.jsp ..\..\hold\wSPLDPrecautionaryStatement.jsp
move genjs\wSPLDPrecautionaryStatement.js ..\..\hold\genjs\wSPLDPrecautionaryStatement.js
move wSPLDPrecautionary.jsp ..\..\hold\wSPLDPrecautionary.jsp
move genjs\wSPLDPrecautionary.js ..\..\hold\genjs\wSPLDPrecautionary.js
move wSPLDOrganismClaimsStatement.jsp ..\..\hold\wSPLDOrganismClaimsStatement.jsp
move genjs\wSPLDOrganismClaimsStatement.js ..\..\hold\genjs\wSPLDOrganismClaimsStatement.js
move wSPLDOrganismClaims.jsp ..\..\hold\wSPLDOrganismClaims.jsp
move genjs\wSPLDOrganismClaims.js ..\..\hold\genjs\wSPLDOrganismClaims.js
move wSPLDNewPhysicalLabelDef.jsp ..\..\hold\wSPLDNewPhysicalLabelDef.jsp
move genjs\wSPLDNewPhysicalLabelDef.js ..\..\hold\genjs\wSPLDNewPhysicalLabelDef.js
move wSPLDMoveDirectionsForUseSections.jsp ..\..\hold\wSPLDMoveDirectionsForUseSections.jsp
move genjs\wSPLDMoveDirectionsForUseSections.js ..\..\hold\genjs\wSPLDMoveDirectionsForUseSections.js
move wSPLDMarketingUsageRemove.jsp ..\..\hold\wSPLDMarketingUsageRemove.jsp
move genjs\wSPLDMarketingUsageRemove.js ..\..\hold\genjs\wSPLDMarketingUsageRemove.js
move wSPLDMarketingStatement.jsp ..\..\hold\wSPLDMarketingStatement.jsp
move genjs\wSPLDMarketingStatement.js ..\..\hold\genjs\wSPLDMarketingStatement.js
move wSPLDMarketingSection.jsp ..\..\hold\wSPLDMarketingSection.jsp
move genjs\wSPLDMarketingSection.js ..\..\hold\genjs\wSPLDMarketingSection.js
move wSPLDMarketing.jsp ..\..\hold\wSPLDMarketing.jsp
move genjs\wSPLDMarketing.js ..\..\hold\genjs\wSPLDMarketing.js
move wSPLDListSubregProducts.jsp ..\..\hold\wSPLDListSubregProducts.jsp
move genjs\wSPLDListSubregProducts.js ..\..\hold\genjs\wSPLDListSubregProducts.js
move wSPLDIngredientsStatement.jsp ..\..\hold\wSPLDIngredientsStatement.jsp
move genjs\wSPLDIngredientsStatement.js ..\..\hold\genjs\wSPLDIngredientsStatement.js
move wSPLDIngredients.jsp ..\..\hold\wSPLDIngredients.jsp
move genjs\wSPLDIngredients.js ..\..\hold\genjs\wSPLDIngredients.js
move wSPLDHumanHazard.jsp ..\..\hold\wSPLDHumanHazard.jsp
move genjs\wSPLDHumanHazard.js ..\..\hold\genjs\wSPLDHumanHazard.js
move wSPLDHazardStatement.jsp ..\..\hold\wSPLDHazardStatement.jsp
move genjs\wSPLDHazardStatement.js ..\..\hold\genjs\wSPLDHazardStatement.js
move wSPLDHazardSection.jsp ..\..\hold\wSPLDHazardSection.jsp
move genjs\wSPLDHazardSection.js ..\..\hold\genjs\wSPLDHazardSection.js
move wSPLDHazard.jsp ..\..\hold\wSPLDHazard.jsp
move genjs\wSPLDHazard.js ..\..\hold\genjs\wSPLDHazard.js
move wSPLDFirstAidStatement.jsp ..\..\hold\wSPLDFirstAidStatement.jsp
move genjs\wSPLDFirstAidStatement.js ..\..\hold\genjs\wSPLDFirstAidStatement.js
move wSPLDFirstAid.jsp ..\..\hold\wSPLDFirstAid.jsp
move genjs\wSPLDFirstAid.js ..\..\hold\genjs\wSPLDFirstAid.js
move wSPLDDirectionsUsageRemove.jsp ..\..\hold\wSPLDDirectionsUsageRemove.jsp
move genjs\wSPLDDirectionsUsageRemove.js ..\..\hold\genjs\wSPLDDirectionsUsageRemove.js
move wSPLDDirectionsForUseStatement.jsp ..\..\hold\wSPLDDirectionsForUseStatement.jsp
move genjs\wSPLDDirectionsForUseStatement.js ..\..\hold\genjs\wSPLDDirectionsForUseStatement.js
move wSPLDDirectionsForUseSection.jsp ..\..\hold\wSPLDDirectionsForUseSection.jsp
move genjs\wSPLDDirectionsForUseSection.js ..\..\hold\genjs\wSPLDDirectionsForUseSection.js
move wSPLDDirectionsForUse.jsp ..\..\hold\wSPLDDirectionsForUse.jsp
move genjs\wSPLDDirectionsForUse.js ..\..\hold\genjs\wSPLDDirectionsForUse.js
move wSPLDDeleteSurfacesStatement.jsp ..\..\hold\wSPLDDeleteSurfacesStatement.jsp
move genjs\wSPLDDeleteSurfacesStatement.js ..\..\hold\genjs\wSPLDDeleteSurfacesStatement.js
move wSPLDDeleteStorageDisposalStatement.jsp ..\..\hold\wSPLDDeleteStorageDisposalStatement.jsp
move genjs\wSPLDDeleteStorageDisposalStatement.js ..\..\hold\genjs\wSPLDDeleteStorageDisposalStatement.js
move wSPLDDeleteStorageDisposalSection.jsp ..\..\hold\wSPLDDeleteStorageDisposalSection.jsp
move genjs\wSPLDDeleteStorageDisposalSection.js ..\..\hold\genjs\wSPLDDeleteStorageDisposalSection.js
move wSPLDDeletePrecautionaryStatement.jsp ..\..\hold\wSPLDDeletePrecautionaryStatement.jsp
move genjs\wSPLDDeletePrecautionaryStatement.js ..\..\hold\genjs\wSPLDDeletePrecautionaryStatement.js
move wSPLDDeletePhysicalLabelDef.jsp ..\..\hold\wSPLDDeletePhysicalLabelDef.jsp
move genjs\wSPLDDeletePhysicalLabelDef.js ..\..\hold\genjs\wSPLDDeletePhysicalLabelDef.js
move wSPLDDeleteMarketingStatement.jsp ..\..\hold\wSPLDDeleteMarketingStatement.jsp
move genjs\wSPLDDeleteMarketingStatement.js ..\..\hold\genjs\wSPLDDeleteMarketingStatement.js
move wSPLDDeleteMarketingSection.jsp ..\..\hold\wSPLDDeleteMarketingSection.jsp
move genjs\wSPLDDeleteMarketingSection.js ..\..\hold\genjs\wSPLDDeleteMarketingSection.js
move wSPLDDeleteIngredientsStatement.jsp ..\..\hold\wSPLDDeleteIngredientsStatement.jsp
move genjs\wSPLDDeleteIngredientsStatement.js ..\..\hold\genjs\wSPLDDeleteIngredientsStatement.js
move wSPLDDeleteHazardStatement.jsp ..\..\hold\wSPLDDeleteHazardStatement.jsp
move genjs\wSPLDDeleteHazardStatement.js ..\..\hold\genjs\wSPLDDeleteHazardStatement.js
move wSPLDSubregProductUpdate.jsp ..\..\hold\wSPLDSubregProductUpdate.jsp
move genjs\wSPLDSubregProductUpdate.js ..\..\hold\genjs\wSPLDSubregProductUpdate.js
move wSPLDDeleteSubregProduct.jsp ..\..\hold\wSPLDDeleteSubregProduct.jsp
move genjs\wSPLDDeleteSubregProduct.js ..\..\hold\genjs\wSPLDDeleteSubregProduct.js
move wSPLDSubregProductsList.jsp ..\..\hold\wSPLDSubregProductsList.jsp
move genjs\wSPLDSubregProductsList.js ..\..\hold\genjs\wSPLDSubregProductsList.js
move wSPLDSLC_ComponentsUpdate.jsp ..\..\hold\wSPLDSLC_ComponentsUpdate.jsp
move genjs\wSPLDSLC_ComponentsUpdate.js ..\..\hold\genjs\wSPLDSLC_ComponentsUpdate.js
move wSPLDSLC_Components.jsp ..\..\hold\wSPLDSLC_Components.jsp
move genjs\wSPLDSLC_Components.js ..\..\hold\genjs\wSPLDSLC_Components.js
move wSPLDNewSLC_SelectMLC.jsp ..\..\hold\wSPLDNewSLC_SelectMLC.jsp
move genjs\wSPLDNewSLC_SelectMLC.js ..\..\hold\genjs\wSPLDNewSLC_SelectMLC.js
move wSPLDDeleteSubregProductSLC.jsp ..\..\hold\wSPLDDeleteSubregProductSLC.jsp
move genjs\wSPLDDeleteSubregProductSLC.js ..\..\hold\genjs\wSPLDDeleteSubregProductSLC.js