copy e:AppTypes.csv
copy e:AppTypes.epa
copy e:AreasOfUse.csv
copy e:AreasOfUse.epa
copy e:Bacteria.csv
copy e:Bacteria.epa
copy e:Claims.csv
copy e:Claims.epa
copy e:cmprdks.bat
copy e:copyhld.bat
copy e:Fungi.csv
copy e:Fungi.epa
copy e:hld2nb.bat
copy e:hld2tom.bat
copy e:index.html
copy e:Keyword.csv
copy e:logout.html
copy e:logout.jsp
copy e:Surfaces.csv
copy e:Surfaces.epa
copy e:Viruses.csv
copy e:Viruses.epa
copy e:wSPLDGraphicalView.jsp.dks
copy e:wStartUpUserLogin.jsp.dks